# -*- coding: utf-8 -*-
"""Stats_FURIA_CS2ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6G66QeleQryhwfjBOFQJwmZ6Otmt5Ng

# Overview lado CT + lado TR
"""

import pandas as pd

stats_geral = '/content/players_furia_stats.html'

pd.read_html(stats_geral)

pd.read_html(stats_geral)[0]

df.info()

df['K/D'].mean()

media_kd_geral = df['K/D'].mean()

df['Rating3.0'].mean()

media_rating_geral = df['Rating3.0'].mean()

df['Rating3.0'].max()

maior_rating = df['Rating3.0'].max()

df['Rating3.0'].min()

menor_rating = df['Rating3.0'].min()

df['Rating3.0'] == maior_rating

selecao = df['Rating3.0'] == maior_rating

df[selecao]

df_maior_rating = df[selecao]

df['Rating3.0'] == menor_rating

selecao_1 = df['Rating3.0'] == menor_rating

df[selecao_1]

df_menor_rating = df[selecao_1]

menor_rating = df_menor_rating[['Player', 'Rating3.0']]

df.sort_values('Rating3.0', ascending=False)

df = df.sort_values('Rating3.0', ascending=False)

df.plot(kind='barh', figsize=(10,8), ylabel='Player', y='Rating3.0', xlabel='Rating3.0', x='Player', color='black')

df.sort_values('Rating3.0', ascending=False)

df[['Player', 'Rating3.0']]

df.sort_values('K/D',ascending=False)

df.sort_values('Rating3.0',ascending=False)

"""# Overview CT"""

stats_ct = '/content/players_furia_stats_ct.html'

pd.read_html(stats_ct)

pd.read_html(stats_ct)[0]

df_ct = pd.read_html(stats_ct)[0]

df_ct.info()

df_ct['K/D'].mean()

df_ct_kd_medio_time = df_ct['K/D'].mean()

df_ct['Rating3.0'].max()

df_ct['Rating3.0'].min()

df['Rating3.0'] == df_ct['Rating3.0'].max()

maior_rating_ct = df['Rating3.0'] == df_ct['Rating3.0'].max()

df_ct['Rating3.0'] == df_ct['Rating3.0'].min()

menor_rating_ct = df_ct['Rating3.0'] == df_ct['Rating3.0'].min()

df_ct[maior_rating_ct]

df_ct[menor_rating_ct]

df_ct = df_ct.sort_values('Rating3.0')

df_ct.plot(kind='barh', figsize=(10,8), x='Player', y='Rating3.0', color='black')

df_ct.sort_values('Rating3.0', ascending=False)

df_ct['Rating3.0'].mean()

media_rating_ct = df_ct['Rating3.0'].mean()

df_ct['K/D'].mean()

media_kd_ct = df_ct['K/D'].mean()

"""# Overview TR"""

stats_tr = '/content/players_furia_stats_tr.html'

pd.read_html(stats_tr)

pd.read_html(stats_tr)[0]

df_tr = pd.read_html(stats_tr)[0]

df_tr['Rating3.0'].mean()

media_rating_tr = df_tr['Rating3.0'].mean()

df_tr['Rating3.0'].max()

df_tr['Rating3.0'].min()

df_tr['Rating3.0'] == df_tr['Rating3.0'].max()

maior_rating_tr = df_tr['Rating3.0'] == df_tr['Rating3.0'].max()

df_tr['Rating3.0'] == df_tr['Rating3.0'].min()

menor_rating_tr = df_tr['Rating3.0'] == df_tr['Rating3.0'].min()

df_tr[maior_rating_tr]

df_tr[menor_rating_tr]

df_tr = df_tr.sort_values('Rating3.0')

df_tr.plot(kind='barh', figsize=(10,8), x='Player', y='Rating3.0', color='black')

df_tr.sort_values('Rating3.0', ascending=False)

"""# Comparações"""

df_ct.plot(kind='barh', figsize=(10,8), x='Player', y='Rating3.0', xlabel='LADO CT', color='black')

df_tr.plot(kind='barh', figsize=(10,8), x='Player', y='Rating3.0', xlabel='LADO TR', color='black')

df_ct.sort_values('Rating3.0', ascending=False)

df_tr.sort_values('Rating3.0', ascending=False)

media_rating_ct

media_rating_tr

media_rating_tr - media_rating_ct

df_ct.sort_values('K/D', ascending=False)

df_tr.sort_values('K/D', ascending=False)

df_ct = df_ct.sort_values('K/D', ascending=False)

df_tr = df_tr.sort_values('K/D', ascending=False)

df_ct['K/D'].max()-df_tr['K/D'].max()

diferenca_rating = df_ct['K/D'].max()-df_tr['K/D'].max()